### ISSUE TITLE
上架谷歌商店

### ISSUE THREAD

**Issue by brizer** [yutent/dns-flush#1]
可以上架谷歌商店吗？方便下载和安装。

**Comment by yutent** [comment]
哈哈, 比较笨, 没找到怎么上架到商店。其实商店里有一个类似的插件的。

**Comment by brizer** [comment]
> 哈哈, 比较笨, 没找到怎么上架到商店。其实商店里有一个类似的插件的(大概很久没更新了)。
> 我这插件的名字和小logo还是直接用它的。

可以研究下的，补个manifest就可以了，就是谷歌开发者账号需要5美元注册而已。

**Comment by yutent** [comment]
> 可以研究下的，补个manifest就可以了，就是谷歌开发者账号需要5美元注册而已。

就是没找到怎么申请开发者
